api:
  identifier: "IdTuna"
  port: 9541

logger:
  options:
    level: trace

mongodb:
  url: "mongodb://localhost:27017"
  database: "Tuna"
  options:
    useUnifielTopology: true
    useNewUrlParser: true
